routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'HomeController@view_articles');
Route::get('/about_us', 'HomeController@view_about_us');
Route::get('/contact_us', 'HomeController@view_contact_us');

Route::get('/change_personal_info/{id}', 'ServiceController@show_change_info')->name('change_personal_info.show');
Route::patch('/change_personal_info/update/{id}', 'ServiceController@update_change_info')->name('change_personal_info.update');

Route::get('/my_dog_lists','ServiceController@index_my_list')->name('my_lists.index');
Route::get('/my_dog_lists/show','ServiceController@show_my_list')->name('my_lists.show');
Route::patch('/my_dog_lists/add/{id}', 'ServiceController@add_my_list')->name('my_lists.add');
Route::delete('/my_dog_lists/delete/{id}', 'ServiceController@delete_my_list')->name('my_lists.delete');

Route::get('/search', 'ServiceController@microchip_no_search')->name('microchip_no.search');
Route::get('/install_search', 'ServiceController@microchip_install_search')->name('microchip_no.install_search');

Route::post('/request_change_owner', 'ServiceController@store_request_change_owner')->name('request_change_owners.store');

Route::post('/request_install', 'ServiceController@request_install')->name('request_install.store');

// Dynamic Dropdown
Route::post('orders/dropdown_province','ManageOrderController@dropdown_province')->name('orders.dropdown_province');
Route::post('orders/dropdown_amphures','ManageOrderController@dropdown_amphures')->name('orders.dropdown_amphures');
Route::post('orders/delivery_fee','ManageOrderController@delivery_fee')->name('orders.delivery_fee');

//Route for admin
Route::group(['prefix' => 'admin'], function(){
    Route::group(['middleware' => ['is_admin']], function(){
        Route::get('/dashboard', 'RoleController@dashboard_admin')->name('dashboard.admin');

        Route::resource('manage_articles','ManageArticleController', ['except' => ['show']]);

        Route::resource('manage_users','ManageUserController', ['except' => ['show']]);

        Route::get('manage_home', 'ManageWebController@view_manage_home')->name('home.manage');
        Route::patch('manage_home/{id}', 'ManageWebController@manage_home')->name('home.update');
        Route::get('manage_about_us', 'ManageWebController@view_manage_about_us')->name('about_us.manage');
        Route::patch('manage_about_us/{id}', 'ManageWebController@manage_about_us')->name('about_us.update');
        Route::get('manage_contact_us', 'ManageWebController@view_manage_contact_us')->name('contact_us.manage');
        Route::patch('manage_contact_us/{id}', 'ManageWebController@manage_contact_us')->name('contact_us.update');

        Route::resource('manage_dog_farms', 'ManageDogFarmController', ['except' => ['create','show','edit']]);
        Route::get('manage_dog_farms/{id}/{dog_farm_name}', 'ManageDogFarmController@show')->name('manage_dog_farms.show');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/ตัวผู้', 'ManageDogFarmController@show_male')->name('manage_dog_farms.show_male');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/ตัวเมีย', 'ManageDogFarmController@show_female')->name('manage_dog_farms.show_female');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/{dog_breed}', 'ManageDogFarmController@sort_breed')->name('manage_dog_farms.sort_breed');

        Route::resource('manage_dog_breeds', 'ManageDogBreedController', ['except' => ['create','show','edit']]);
        Route::get('manage_dog_breeds/{id}/{dog_breed}', 'ManageDogBreedController@show')->name('manage_dog_breeds.show');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/ตัวผู้', 'ManageDogBreedController@show_male')->name('manage_dog_breeds.show_male');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/ตัวเมีย', 'ManageDogBreedController@show_female')->name('manage_dog_breeds.show_female');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/{dog_farm_name}', 'ManageDogBreedController@sort_farm')->name('manage_dog_breeds.sort_farm');

        Route::resource('manage_dogs', 'ManageDogController');
        Route::get('manage_dogs/sort_breed/{dog_breed}', 'ManageDogController@index_sort_breed')->name('manage_dogs.index_sort_breed');
        Route::get('manage_dogs/sort_farm/{dog_farm_name}', 'ManageDogController@index_sort_farm')->name('manage_dogs.index_sort_farm');
        Route::get('manage_dogs/sort_sex/{dog_sex}', 'ManageDogController@index_sort_sex')->name('manage_dogs.index_sort_sex');
        Route::get('manage_dogs/sort_status/{dog_status}', 'ManageDogController@index_sort_status')->name('manage_dogs.index_sort_status');
        Route::get('manage_dogs/show_install/{id}', 'ManageDogController@show_install')->name('manage_dogs.show_install');

        Route::resource('manage_microchips', 'ManageMicrochipController', ['except' => ['create','edit']]);
        Route::get('manage_microchips/sort_status/{microchip_status}', 'ManageMicrochipController@index_sort_status')->name('manage_microchips.index_sort_status');
        Route::get('manage_microchips/show_install/{id}', 'ManageMicrochipController@show_install')->name('manage_microchips.show_install');
        
        Route::resource('manage_orders', 'ManageOrderController', ['except' => ['create','edit','update']]);
        Route::get('manage_orders/sort_deliveryman/{name}', 'ManageOrderController@index_sort_deliveryman')->name('manage_orders.index_sort_deliveryman');
        Route::get('manage_orders/sort_status/{order_status}', 'ManageOrderController@index_sort_status')->name('manage_orders.index_sort_status');
        Route::get('manage_orders/create_dog_order/{manage_order}', 'ManageOrderController@create_dog')->name('manage_orders.create_dog');
        Route::get('manage_orders/create_microchip_order/{manage_order}', 'ManageOrderController@create_microchip')->name('manage_orders.create_microchip');
        Route::get('manage_orders/create_install_order/{manage_order}', 'ManageOrderController@create_install')->name('manage_orders.create_install');
        Route::patch('manage_orders/{manage_order}', 'ManageOrderController@confirm')->name('manage_orders.confirm');
        Route::patch('manage_orders/resend/{manage_order}', 'ManageOrderController@resend')->name('manage_orders.resend');
        
        Route::get('sells','SellController@index')->name('sells.index');
        Route::get('sells/{id}', 'SellController@show')->name('sells.show');
        
        Route::get('manage_request_change_owners','ServiceController@index_request_change_owner')->name('request_change_owners.index');
        Route::put('manage_request_change_owners/{id}','ServiceController@confirm_request_change_owner')->name('request_change_owners.confirm');
        Route::delete('manage_request_change_owners/{id}','ServiceController@delete_request_change_owner')->name('request_change_owners.delete');
        
        Route::get('manage_request_installs','ServiceController@index_request_install')->name('request_install.index');
        Route::patch('manage_request_installs/{id}', 'ServiceController@confirm_request_install')->name('request_install.confirm');
        Route::delete('manage_request_installs/{id}','ServiceController@delete_request_install')->name('request_install.delete');

        // Report
        Route::get('install_microchip/report','ReportController@report_install')->name('report_install.index');
        Route::get('install_microchip/report_search','ReportController@search_report_install')->name('report_install.search');
        Route::get('pdf_install_microchip/{id}','ReportController@pdf_install_microchip')->name('pdf_install_microchip');
        Route::get('pdf_sell/{id}','ReportController@pdf_sell')->name('pdf_sell');
        Route::get('total_sell','ReportController@total_sell')->name('total_sell.index');
        Route::get('total_sell/sort','ReportController@total_sell_sort')->name('total_sell.sort');
    });
});

//Route for deliveryman
Route::group(['prefix' => 'deliveryman'], function(){
    Route::group(['middleware' => ['is_deliveryman']], function(){
        Route::get('/dashboard', 'RoleController@dashboard_deliveryman')->name('dashboard.deliveryman');

        Route::get('manage_orders', 'ManageOrderController@index_deliveryman')->name('manage_orders.index_deliveryman');
        Route::get('manage_orders/{id}', 'ManageOrderController@show_deliveryman')->name('manage_orders.show_deliveryman');
        Route::patch('manage_orders/{manage_order}', 'ManageOrderController@confirm_deliveryman')->name('manage_orders.confirm_deliveryman');
        Route::get('manage_orders/sort_status/{order_status}', 'ManageOrderController@index_deliveryman_sort_status')->name('manage_orders.index_deliveryman_sort_status');

        Route::resource('manage_transports', 'ManageTransportController');

        Route::get('pdf_order/{id}','ReportController@pdf_order')->name('pdf_order');
    });
});

app/Http/Controllers/ManageArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;

class ManageArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $articles = Article::paginate(20);

        return view('manage_articles.index',compact('articles'))->with('i', (request()->input('page', 1) - 1) * 20);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('manage_articles.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        request()->validate([
            'article_image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if ($request->hasfile('article_image')){
            $image_name = time().'.'.request()->article_image->getClientOriginalExtension();
            request()->article_image->move(public_path('image/articles'), $image_name);
            $article = new Article([
                'article_name' => $request->article_name,
                'article_content' => $request->article_content,
                'article_image' => $image_name,
            ]);
            $article->save();
        }
        else {
            $article = new Article([
                'article_name' => $request->article_name,
                'article_content' => $request->article_content,
            ]);
            $article->save();
        }

        return redirect()->route('manage_articles.index')->with('success','เพิ่มบทความแล้ว');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $article = Article::find($id);

        return view('manage_articles.edit',compact('article'));                
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        request()->validate([
            'article_image' => 'image|mimes:jpeg,png,jpg,gif,svg|max:2048',
        ]);

        if ($request->hasfile('article_image')){
            $image_name = time().'.'.request()->article_image->getClientOriginalExtension();
            request()->article_image->move(public_path('image/articles'), $image_name);

            $article = Article::find($id);
            $article->article_name = $request->article_name;
            $article->article_content = $request->article_content;
            $article->article_image = $image_name; 
            $article->save();
        }
        else {
            $article = Article::find($id);
            $article->article_name = $request->article_name;
            $article->article_content = $request->article_content;
            $article->save();
        }
        
        return redirect()->route('manage_articles.index')-> with('success','แก้ไขบทความแล้ว');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $article = Article::find($id);
        $article->delete();

        return redirect()->route('manage_articles.index')->with('success','ลบบทความแล้ว');
    }
}

resources/views/manage_articles/create.blade.php
@extends('layouts.admin')
@section('content')
<div id="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-11">
                {{-- Breadcrumb --}}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white shadow-sm">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard.admin') }}">แดชบอร์ด</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('manage_articles.index') }}">จัดการบทความ</a></li>
                        <li class="breadcrumb-item active" aria-current="page">เพิ่มบทความ</li>
                    </ol>
                </nav>

                <div class="card shadow-sm mb-3">
                    <div class="card-body">
                        {{-- Message --}}
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
                            <h1 class="h2">เพิ่มบทความ</h1>
                        </div>

                        <form action="{{ route('manage_articles.store') }}" method="POST" enctype="multipart/form-data">
                            @csrf
                            <div class="form-group">
                                <label>ชื่อบทความ</label>
                                <input type="text" class="form-control" name="article_name" required>
                            </div>
                            <div class="form-group">
                                <label>เนื้อหาบทความ</label>
                                <textarea class="form-control" name="article_content" rows="4" required></textarea>
                            </div>
                            <div class="form-group">
                                <label>รูปภาพ</label>
                                <input type="file" class="form-control" name="article_image">
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="btn btn-main">บันทึกข้อมูล</button>
                                <button type="reset" class="btn btn-secondary">ยกเลิก</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/manage_articles/edit.blade.php
@extends('layouts.admin')
@section('content')
<div id="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-11">
                {{-- Breadcrumb --}}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white shadow-sm">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard.admin') }}">แดชบอร์ด</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('manage_articles.index') }}">จัดการบทความ</a></li>
                        <li class="breadcrumb-item active" aria-current="page">แก้ไขบทความ</li>
                    </ol>
                </nav>

                <div class="card shadow-sm mb-3">
                    <div class="card-body">
                        {{-- Message --}}
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        <div
                            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
                            <h1 class="h2">แก้ไขบทความ</h1>
                        </div>

                        <form action="{{ route('manage_articles.update',$article->id) }}" method="POST"
                            enctype="multipart/form-data">
                            @csrf
                            @method('PUT')
                            <div class="form-group">
                                <label>ชื่อบทความ</label>
                                <input type="text" class="form-control" name="article_name"
                                    value="{{ $article->article_name }}" required>
                            </div>
                            <div class="form-group">
                                <label>เนื้อหาบทความ</label>
                                <textarea class="form-control" name="article_content" rows="4"
                                    required>{{ $article->article_content }}</textarea>
                            </div>
                            <div class="form-group">
                                @if ($article->article_image != null)
                                <label>รูปภาพ</label>
                                <div class="mb-3">
                                    <img src="{{ asset('image/articles/'.$article->article_image) }}" class="rounded"
                                        width="30%">
                                </div>
                                <label>เปลี่ยนรูปภาพ</label>
                                <input type="file" class="form-control" name="article_image">
                                @else
                                <label>รูปภาพ</label>
                                <input type="file" class="form-control" name="article_image">
                                @endif
                            </div>
                            <div class="form-group text-center">
                                <button type="submit" class="btn btn-main">บันทึกข้อมูล</button>
                                <button type="reset" class="btn btn-secondary">ยกเลิก</button>
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/manage_articles/index.blade.php
@extends('layouts.admin')
@section('content')
<div id="page-content">
    <div class="container-fluid">
        <div class="row justify-content-center">
            <div class="col-md-11">
                {{-- Breadcrumb --}}
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb bg-white shadow-sm">
                        <li class="breadcrumb-item"><a href="{{ route('dashboard.admin') }}">แดชบอร์ด</a></li>
                        <li class="breadcrumb-item active" aria-current="page">จัดการบทความ</li>
                    </ol>
                </nav>

                <div class="card shadow-sm mb-3">
                    <div class="card-body">
                        {{-- Message --}}
                        @if ($message = Session::get('success'))
                        <div class="alert alert-success alert-dismissible fade show" role="alert">
                            {{ $message }}
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                        </div>
                        @endif

                        <div
                            class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3">
                            <h1 class="h2">จัดการบทความ</h1>
                            <div class="mb-2 mb-md-0">
                                <div class="btn-group">
                                    <a class="btn btn-main" href="{{ route('manage_articles.create') }}"
                                        role="button">เพิ่มบทความ</a>
                                </div>
                            </div>
                        </div>

                        <div class="table-responsive">
                            <table class="table table-borderless">
                                <thead class="thead-dark">
                                    <tr>
                                        <th>ลำดับ</th>
                                        <th>รหัส</th>
                                        <th>บทความ</th>
                                        <th>สร้างเมื่อ</th>
                                        <th>ปรับปรุงเมื่อ</th>
                                        <th>จัดการ</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @forelse ($articles as $article)
                                    <tr>
                                        <td>{{ ++$i }}</td>
                                        <td>{{ $article->id }}</td>
                                        <td>{{ $article->article_name }}</td>
                                        <td>{{ $article->created_at->format('Y-m-d') }}</td>
                                        <td>{{ $article->updated_at->format('Y-m-d') }}</td>
                                        <td>
                                            <div class="btn-group" role="group">
                                                <a class="btn btn-link text-dark"
                                                    href="{{ route('manage_articles.edit',$article->id) }}"
                                                    role="button">
                                                    <i class="fas fa-edit"></i>
                                                </a>
                                                <!-- Trigger delete modal -->
                                                <button type="button" class="btn btn-link text-dark" data-toggle="modal"
                                                    data-target="#delete{{ $article->id }}Modal">
                                                    <i class="fas fa-trash"></i>
                                                </button>
                                                <!-- Delete Modal -->
                                                <div class="modal fade" id="delete{{ $article->id }}Modal" tabindex="-1"
                                                    role="dialog" aria-labelledby="delete{{ $article->id }}ModalLabel"
                                                    aria-hidden="true">
                                                    <div class="modal-dialog" role="document">
                                                        <div class="modal-content">
                                                            <div class="modal-header border-0">
                                                                <h5 class="modal-title"
                                                                    id="delete{{ $article->id }}ModalLabel">
                                                                    ยืนยันการลบบทความ
                                                                </h5>
                                                                <button type="button" class="close" data-dismiss="modal"
                                                                    aria-label="Close">
                                                                    <span aria-hidden="true">&times;</span>
                                                                </button>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p>คุณต้องการลบบทความ รหัส {{ $article->id }}
                                                                    "{{ $article->article_name }}"
                                                                    หรือไม่?</p>
                                                                <div class="form-group text-right">
                                                                    <form
                                                                        action="{{ route('manage_articles.destroy',$article->id) }}"
                                                                        method="POST">
                                                                        @csrf
                                                                        @method('DELETE')
                                                                        <button type="button" class="btn btn-secondary"
                                                                            data-dismiss="modal">ยกเลิก</button>
                                                                        <button type="submit"
                                                                            class="btn btn-main">ลบข้อมูล</button>
                                                                    </form>
                                                                </div>
                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>

                                        </td>
                                    </tr>
                                    @empty
                                    <tr>
                                        <td>ไม่มีข้อมูล</td>
                                    </tr>
                                    @endforelse
                                </tbody>
                            </table>

                            {{-- Pagination --}}
                            <div class="d-flex justify-content-center">
                                {!! $articles->links() !!}
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection