routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes(['reset' => false]);

Route::get('/', 'HomeController@index')->name('home');
Route::get('/articles', 'HomeController@view_articles');
Route::get('/about_us', 'HomeController@view_about_us');
Route::get('/contact_us', 'HomeController@view_contact_us');

Route::get('/change_personal_info/{id}', 'ServiceController@show_change_info')->name('change_personal_info.show');
Route::patch('/change_personal_info/update/{id}', 'ServiceController@update_change_info')->name('change_personal_info.update');

Route::get('/my_dog_lists','ServiceController@index_my_list')->name('my_lists.index');
Route::get('/my_dog_lists/show','ServiceController@show_my_list')->name('my_lists.show');
Route::patch('/my_dog_lists/add/{id}', 'ServiceController@add_my_list')->name('my_lists.add');
Route::delete('/my_dog_lists/delete/{id}', 'ServiceController@delete_my_list')->name('my_lists.delete');

Route::get('/search', 'ServiceController@microchip_no_search')->name('microchip_no.search');
Route::get('/install_search', 'ServiceController@microchip_install_search')->name('microchip_no.install_search');

Route::post('/request_change_owner', 'ServiceController@store_request_change_owner')->name('request_change_owners.store');

Route::post('/request_install', 'ServiceController@request_install')->name('request_install.store');

// Dynamic Dropdown
Route::post('orders/dropdown_province','ManageOrderController@dropdown_province')->name('orders.dropdown_province');
Route::post('orders/dropdown_amphures','ManageOrderController@dropdown_amphures')->name('orders.dropdown_amphures');
Route::post('orders/delivery_fee','ManageOrderController@delivery_fee')->name('orders.delivery_fee');

//Route for admin
Route::group(['prefix' => 'admin'], function(){
    Route::group(['middleware' => ['is_admin']], function(){
        Route::get('/dashboard', 'RoleController@dashboard_admin')->name('dashboard.admin');

        Route::resource('manage_articles','ManageArticleController', ['except' => ['show']]);

        Route::resource('manage_users','ManageUserController', ['except' => ['show']]);

        Route::get('manage_home', 'ManageWebController@view_manage_home')->name('home.manage');
        Route::patch('manage_home/{id}', 'ManageWebController@manage_home')->name('home.update');
        Route::get('manage_about_us', 'ManageWebController@view_manage_about_us')->name('about_us.manage');
        Route::patch('manage_about_us/{id}', 'ManageWebController@manage_about_us')->name('about_us.update');
        Route::get('manage_contact_us', 'ManageWebController@view_manage_contact_us')->name('contact_us.manage');
        Route::patch('manage_contact_us/{id}', 'ManageWebController@manage_contact_us')->name('contact_us.update');

        Route::resource('manage_dog_farms', 'ManageDogFarmController', ['except' => ['create','show','edit']]);
        Route::get('manage_dog_farms/{id}/{dog_farm_name}', 'ManageDogFarmController@show')->name('manage_dog_farms.show');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/ตัวผู้', 'ManageDogFarmController@show_male')->name('manage_dog_farms.show_male');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/ตัวเมีย', 'ManageDogFarmController@show_female')->name('manage_dog_farms.show_female');
        Route::get('manage_dog_farms/{id}/{dog_farm_name}/{dog_breed}', 'ManageDogFarmController@sort_breed')->name('manage_dog_farms.sort_breed');

        Route::resource('manage_dog_breeds', 'ManageDogBreedController', ['except' => ['create','show','edit']]);
        Route::get('manage_dog_breeds/{id}/{dog_breed}', 'ManageDogBreedController@show')->name('manage_dog_breeds.show');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/ตัวผู้', 'ManageDogBreedController@show_male')->name('manage_dog_breeds.show_male');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/ตัวเมีย', 'ManageDogBreedController@show_female')->name('manage_dog_breeds.show_female');
        Route::get('manage_dog_breeds/{id}/{dog_breed}/{dog_farm_name}', 'ManageDogBreedController@sort_farm')->name('manage_dog_breeds.sort_farm');

        Route::resource('manage_dogs', 'ManageDogController');
        Route::get('manage_dogs/sort_breed/{dog_breed}', 'ManageDogController@index_sort_breed')->name('manage_dogs.index_sort_breed');
        Route::get('manage_dogs/sort_farm/{dog_farm_name}', 'ManageDogController@index_sort_farm')->name('manage_dogs.index_sort_farm');
        Route::get('manage_dogs/sort_sex/{dog_sex}', 'ManageDogController@index_sort_sex')->name('manage_dogs.index_sort_sex');
        Route::get('manage_dogs/sort_status/{dog_status}', 'ManageDogController@index_sort_status')->name('manage_dogs.index_sort_status');
        Route::get('manage_dogs/show_install/{id}', 'ManageDogController@show_install')->name('manage_dogs.show_install');

        Route::resource('manage_microchips', 'ManageMicrochipController', ['except' => ['create','edit']]);
        Route::get('manage_microchips/sort_status/{microchip_status}', 'ManageMicrochipController@index_sort_status')->name('manage_microchips.index_sort_status');
        Route::get('manage_microchips/show_install/{id}', 'ManageMicrochipController@show_install')->name('manage_microchips.show_install');
        
        Route::resource('manage_orders', 'ManageOrderController', ['except' => ['create','edit','update']]);
        Route::get('manage_orders/sort_deliveryman/{name}', 'ManageOrderController@index_sort_deliveryman')->name('manage_orders.index_sort_deliveryman');
        Route::get('manage_orders/sort_status/{order_status}', 'ManageOrderController@index_sort_status')->name('manage_orders.index_sort_status');
        Route::get('manage_orders/create_dog_order/{manage_order}', 'ManageOrderController@create_dog')->name('manage_orders.create_dog');
        Route::get('manage_orders/create_microchip_order/{manage_order}', 'ManageOrderController@create_microchip')->name('manage_orders.create_microchip');
        Route::get('manage_orders/create_install_order/{manage_order}', 'ManageOrderController@create_install')->name('manage_orders.create_install');
        Route::patch('manage_orders/{manage_order}', 'ManageOrderController@confirm')->name('manage_orders.confirm');
        Route::patch('manage_orders/resend/{manage_order}', 'ManageOrderController@resend')->name('manage_orders.resend');
        
        Route::get('sells','SellController@index')->name('sells.index');
        Route::get('sells/{id}', 'SellController@show')->name('sells.show');
        
        Route::get('manage_request_change_owners','ServiceController@index_request_change_owner')->name('request_change_owners.index');
        Route::put('manage_request_change_owners/{id}','ServiceController@confirm_request_change_owner')->name('request_change_owners.confirm');
        Route::delete('manage_request_change_owners/{id}','ServiceController@delete_request_change_owner')->name('request_change_owners.delete');
        
        Route::get('manage_request_installs','ServiceController@index_request_install')->name('request_install.index');
        Route::patch('manage_request_installs/{id}', 'ServiceController@confirm_request_install')->name('request_install.confirm');
        Route::delete('manage_request_installs/{id}','ServiceController@delete_request_install')->name('request_install.delete');

        // Report
        Route::get('install_microchip/report','ReportController@report_install')->name('report_install.index');
        Route::get('install_microchip/report_search','ReportController@search_report_install')->name('report_install.search');
        Route::get('pdf_install_microchip/{id}','ReportController@pdf_install_microchip')->name('pdf_install_microchip');
        Route::get('pdf_sell/{id}','ReportController@pdf_sell')->name('pdf_sell');
        Route::get('total_sell','ReportController@total_sell')->name('total_sell.index');
        Route::get('total_sell/sort','ReportController@total_sell_sort')->name('total_sell.sort');
    });
});

//Route for deliveryman
Route::group(['prefix' => 'deliveryman'], function(){
    Route::group(['middleware' => ['is_deliveryman']], function(){
        Route::get('/dashboard', 'RoleController@dashboard_deliveryman')->name('dashboard.deliveryman');

        Route::get('manage_orders', 'ManageOrderController@index_deliveryman')->name('manage_orders.index_deliveryman');
        Route::get('manage_orders/{id}', 'ManageOrderController@show_deliveryman')->name('manage_orders.show_deliveryman');
        Route::patch('manage_orders/{manage_order}', 'ManageOrderController@confirm_deliveryman')->name('manage_orders.confirm_deliveryman');
        Route::get('manage_orders/sort_status/{order_status}', 'ManageOrderController@index_deliveryman_sort_status')->name('manage_orders.index_deliveryman_sort_status');

        Route::resource('manage_transports', 'ManageTransportController');

        Route::get('pdf_order/{id}','ReportController@pdf_order')->name('pdf_order');
    });
});

resources/views/dashboards/admin.blade.php
@extends('layouts.admin')
@section('content')
<div id="page-content">
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <!-- Icon Cards-->
                <div class="row">
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-main shadow-sm h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-main mb-1"><a
                                                href="{{ route('manage_dogs.index') }}">จำนวนสุนัข</a>
                                        </div>
                                        <div class="mr-5">{{ $count_dog }} ตัว</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-dog fa-3x text-black-50"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-main shadow-sm h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-main mb-1">
                                            <a href="{{ route('manage_microchips.index') }}">จำนวนไมโครชิพ</a>
                                        </div>
                                        <div class="mr-5">{{ $count_microchip }} ชิ้น</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-microchip fa-3x text-black-50"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-main shadow-sm h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-main mb-1"><a
                                                href="{{ route('manage_dog_farms.index') }}">จำนวนฟาร์มสุนัข</a></div>
                                        <div class="mr-5">{{ $count_dog_farm }} ฟาร์ม</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-warehouse fa-3x text-black-50"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-xl-3 col-md-6 mb-4">
                        <div class="card border-left-main shadow-sm h-100 py-2">
                            <div class="card-body">
                                <div class="row no-gutters align-items-center">
                                    <div class="col mr-2">
                                        <div class="text-xs font-weight-bold text-main mb-1"><a
                                                href="{{ route('manage_users.index') }}">ผู้ใช้งานระบบ</a></div>
                                        <div class="mr-5">{{ $count_user }} คน</div>
                                    </div>
                                    <div class="col-auto">
                                        <i class="fas fa-users fa-3x text-black-50"></i>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Chart -->
                {{-- <div class="card shadow-sm mb-4">
                    <div class="card-header bg-white border-0">
                        <div class="text-xs font-weight-bold text-main mb-1">
                            <i class="fas fa-chart-area"></i> Area Chart
                        </div>
                    </div>
                    <div class="card-body">
                        <img src="{{ asset('image/charts/area_chart.png') }}" width="100%">
                    </div>
                </div> --}}
                <div class="row">
                    <div class="col-lg-8">
                        <div class="card shadow-sm h-100 mb-4">
                            <div class="card-header bg-white border-0">
                                <div class="text-xs font-weight-bold text-main mb-1">
                                    <i class="fas fa-chart-bar"></i> จำนวนการขาย
                                </div>
                            </div>
                            <div class="card-body">
                                <div style="width:100%">
                                    {!! $sell_chart->container() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="card shadow-sm h-100 mb-4">
                            <div class="card-header bg-white border-0">
                                <div class="text-xs font-weight-bold text-main mb-1">
                                    <i class="fas fa-chart-pie"></i> สัดส่วนเพศ
                                </div>
                            </div>
                            <div class="card-body">
                                <div style="width:100%">
                                    {!! $dog_gender_chart->container() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{!! $sell_chart->script() !!}
{!! $dog_gender_chart->script() !!}
@endsection

resources/views/dashboards/deliveryman.blade.php
@extends('layouts.deliveryman')
@section('content')
<div id="page-content">
    <div class="container-fluid py-4">
        <div class="row justify-content-center">
            <div class="col-md-11">
                <!-- Chart -->
                <div class="row">
                    <div class="col-lg-8">
                        <!-- Icon Cards-->
                        <div class="row">
                            <div class="col-lg-6 mb-4">
                                <div class="card border-left-main shadow-sm h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-main mb-1"><a
                                                        href="{{ route('manage_orders.index_deliveryman') }}">รายการจัดส่งสินค้า</a>
                                                </div>
                                                <div class="mr-5">{{ $count_order }} รายการ</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-truck fa-3x text-black-50"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="col-lg-6 mb-4">
                                <div class="card border-left-main shadow-sm h-100 py-2">
                                    <div class="card-body">
                                        <div class="row no-gutters align-items-center">
                                            <div class="col mr-2">
                                                <div class="text-xs font-weight-bold text-main mb-1">
                                                    <a href="{{ route('manage_transports.index') }}">ช่องทางจัดส่ง</a>
                                                </div>
                                                <div class="mr-5">{{ $count_transport }} ช่องทาง</div>
                                            </div>
                                            <div class="col-auto">
                                                <i class="fas fa-map fa-3x text-black-50"></i>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="card shadow-sm">
                            <div class="card-header bg-white border-0">
                                <div class="text-xs font-weight-bold text-main mb-1">
                                    <i class="fas fa-truck"></i> รายการรอดำเนินการจัดส่งสินค้า
                                </div>
                            </div>
                            <ul class="list-group list-group-flush">
                                @forelse ($new_orders as $new_order)
                                <li class="list-group-item">
                                    <a class="btn btn-link text-dark"
                                        href="{{ route('manage_orders.show_deliveryman',$new_order->id) }}"
                                        role="button"><i class="fas fa-eye"></i></a>
                                    @if ($new_order->order_status == 0 || $new_order->order_status == 2)
                                    <!-- Trigger confrim modal -->
                                    <button type="button" class="btn btn-link text-dark" data-toggle="modal"
                                        data-target="#comfirm{{ $new_order->id }}Modal">
                                        <i class="fas fa-check"></i>
                                    </button>
                                    <!-- Cimfirm Modal -->
                                    <div class="modal fade" id="comfirm{{ $new_order->id }}Modal" tabindex="-1"
                                        role="dialog" aria-labelledby="comfirm{{ $new_order->id }}ModalLabel"
                                        aria-hidden="true">
                                        <div class="modal-dialog" role="document">
                                            <div class="modal-content">
                                                <div class="modal-header border-0">
                                                    <h5 class="modal-title" id="comfirm{{ $new_order->id }}ModalLabel">
                                                        ยืนยันการจัดส่ง
                                                    </h5>
                                                    <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close">
                                                        <span aria-hidden="true">&times;</span>
                                                    </button>
                                                </div>
                                                <div class="modal-body">
                                                    <p>คุณต้องการยืนยันการจัดส่งสินค้า รหัส
                                                        {{ $new_order->id }}
                                                        {{ $new_order->order_dog }} {{ $new_order->order_microchip }}
                                                        หรือไม่?</p>
                                                    <form
                                                        action="{{ route('manage_orders.confirm_deliveryman',$new_order->id) }}"
                                                        method="POST" class="needs-validation" novalidate>
                                                        @csrf
                                                        @method('PATCH')
                                                        <input type="hidden" name="id" value="{{ $new_order->id}}">
                                                        <input type="hidden" name="dog_id"
                                                            value="{{ $new_order->dog_id}}">
                                                        <input type="hidden" name="microchip_id"
                                                            value="{{ $new_order->microchip_id}}">
                                                        <div class="form-row">
                                                            <div class="form-group col-md">
                                                                <label>หมายเลข Tracking</label>
                                                                <input type="text" class="form-control"
                                                                    name="order_tracking_no"
                                                                    placeholder="กรอกหมายเลข Tracking 13 หลัก" required
                                                                    minlength="13" maxlength="13">
                                                                <div class="invalid-feedback">
                                                                    กรุณากรอกหมายเลข Tracking 13 หลัก
                                                                </div>
                                                            </div>
                                                        </div>
                                                        <div class="form-group text-right">
                                                            <button type="button" class="btn btn-secondary"
                                                                data-dismiss="modal">ยกเลิก</button>
                                                            <button type="submit" class="btn btn-main">ยืนยัน</button>
                                                        </div>
                                                    </form>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- Cimfirm Modal -->
                                    @endif
                                    @if ($new_order->order_dog != null && $new_order->order_microchip == null)
                                    รายการจัดส่งสินค้า {{ $new_order->id}} "{{ $new_order->order_dog}}"
                                    @elseif ($new_order->order_microchip != null && $new_order->order_dog == null)
                                    รายการจัดส่งสินค้า {{ $new_order->id}} "{{ $new_order->order_microchip}}"
                                    @elseif ($new_order->order_dog != null && $new_order->order_microchip != null)
                                    รายการจัดส่งสินค้า {{ $new_order->id}} "{{ $new_order->order_dog }} ,
                                    {{ $new_order->order_microchip }}"
                                    @endif
                                    วันกำหนดส่ง {{ $new_order->order_due_date }}
                                </li>
                                @empty
                                <li class="list-group-item">ไม่มีรายการจัดส่งสินค้าใหม่</li>
                                @endforelse
                            </ul>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="card shadow-sm">
                            <div class="card-header bg-white border-0">
                                <div class="text-xs font-weight-bold text-main mb-1">
                                    <i class="fas fa-chart-pie"></i> Pie Chart
                                </div>
                            </div>
                            <div class="card-body">
                                <div style="width:100%">
                                    {!! $transport_chart->container() !!}
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

{!! $transport_chart->script() !!}
@endsection